@tool
extends Node
class_name rooms

enum {
	OUTSIDE = -2,
	NONE = -1,
	DIRT = 0,
	VAULTDOOR = 1,
	ELEVATOR = 2,
	LIVING_ROOM = 3,
	POWER_GENERATOR = 4,
	DINER = 5,
	WATER_TREATMENT = 6,
	STORAGE_ROOM = 7,
	MEDBAY = 8,
	SCIENCE_LAB = 9,
	OVERSEER_OFFICE = 10,
	RADIO_STUDIO = 11,
	WEAPON_WORKSHOP = 12,
	OUTFIT_WORKSHOP = 13
}
